#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# MAGNEETAR MVP — One-Command Deploy
# ═══════════════════════════════════════════════════════════════════════════════
#
# Usage:
#   bash scripts/deploy-mvp.sh
#
# What this does:
#   1. Checks Docker is installed
#   2. Generates secrets if .env doesn't exist
#   3. Builds and starts the server + dashboard + Redis
#   4. Prints the URLs
#
# Requirements:
#   - Docker + Docker Compose (install: https://docs.docker.com/get-docker/)
#   - That's it.
#
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  MAGNEETAR MVP DEPLOY${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""

# ── Step 1: Check Docker ────────────────────────────────────────────────────
if ! command -v docker &> /dev/null; then
    echo -e "${RED}✗ Docker is not installed.${NC}"
    echo "  Install it: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}✗ Docker Compose is not installed.${NC}"
    echo "  Install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi

echo -e "${GREEN}✓ Docker OK${NC}"

# ── Step 2: Generate .env if missing ────────────────────────────────────────
if [ ! -f server/.env ]; then
    echo -e "${YELLOW}→ Generating secure secrets...${NC}"
    bash scripts/generate-env.sh 2>/dev/null || {
        # Fallback: generate .env manually
        {
            echo "# Generated by deploy-mvp.sh"
            echo "MT_API_KEY=$(openssl rand -hex 32)"
            echo "MT_DEVICE_KEY=$(openssl rand -hex 32)"
            echo "MT_JWT_SECRET=$(openssl rand -hex 64)"
            echo "MT_ENCRYPTION_KEY=$(openssl rand -hex 32)"
            echo "MT_ENVIRONMENT=production"
            echo "MT_DB_PATH=/app/data/magneetar.db"
            echo "MT_MEDIA_DIR=/app/media"
            echo "MT_MAX_DEVICES=10"
            echo "MT_RETENTION_DAYS=90"
            echo ""
            echo "# Optional: add your alert credentials below"
            echo "# MT_TWILIO_SID="
            echo "# MT_TWILIO_AUTH_TOKEN="
            echo "# MT_TWILIO_SMS_FROM="
            echo "# MT_FIREBASE_KEY="
            echo "# MT_ALERT_PHONE="
            echo "# MT_ALERT_EMAIL="
        } > server/.env
    }
    echo -e "${GREEN}✓ Secrets generated in server/.env${NC}"
    echo -e "${YELLOW}  ⚠ Save server/.env somewhere safe — it has your master keys${NC}"
else
    echo -e "${GREEN}✓ server/.env exists${NC}"
fi

# ── Step 3: Build and start ─────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}→ Building and starting services...${NC}"
docker compose build --quiet 2>&1 | tail -1
docker compose up -d 2>&1 | tail -3

# ── Step 4: Wait for health ─────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}→ Waiting for server to be ready...${NC}"
for i in $(seq 1 30); do
    if curl -sf http://localhost:8002/health > /dev/null 2>&1; then
        echo -e "${GREEN}✓ Server is healthy${NC}"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo -e "${RED}✗ Server did not start in 30 seconds${NC}"
        echo "  Check logs: docker compose logs server"
        exit 1
    fi
    sleep 1
done

# ── Step 5: Print URLs ──────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  DEPLOYED SUCCESSFULLY${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""
echo "  API:        http://localhost:8002"
echo "  Dashboard:  http://localhost:3000"
echo "  Health:     http://localhost:8002/health"
echo ""
echo "  To expose publicly, set up a Cloudflare Tunnel:"
echo "    cloudflared tunnel --url http://localhost:8002"
echo ""
echo "  To stop:    docker compose down"
echo "  To logs:    docker compose logs -f"
echo ""
